global:
  ms-fake-uno:
    enabled: true
  ms-fake-dos:
    enabled: true

ms-fake-uno:
  externalSecret:
    enabled: true
    secretStoreRef:
      name: floci-secretsmanager
    data:
      - secretKey: DB_PASSWORD
        remoteRef:
          key: prod/app/db
          property: password
  service: #comentario para el commit
    port: 80
    targetPort: 80
  config:
    env:
      enabled: true
      data:
        APP_MODE: uno
        LOG_LEVEL: debug

ms-fake-dos:
  service:
    port: 8080
  config:
    env:
      enabled: true
      data:
        APP_MODE: dos
        LOG_LEVEL: info
  externalSecret:
    enabled: false